### ISSUE TITLE
Windows Display Zoom

### ISSUE THREAD

**Issue by Sickjuicy** [ytmdesktop/ytmdesktop#1158]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I have 2 monitors one at windows zoom 100% and the other at 150%. If I but the windows how I want it on my main monitor and restart the app no problem, but if I do the same thing on my second monitor the one with 150% zoom the windows is much bigger.

I know the issue from antoher app I am currently using and fixed it there, but because at the moment I dont have the time to check your App out I am only making a bug report. Electron has a function for that its called scaleFactor.

Here is the code I made for the fix.

	const scaleFactor = electron.screen.getPrimaryDisplay().scaleFactor;
	const size = config.get("window-size");
	const position = config.get("window-position");

	if (size && size.width && size.height) {
		const scaledSize = {
			width: size.width / scaleFactor,
			height: size.height / scaleFactor,
		};
		win.setSize(scaledSize.width, scaledSize.height);
	}

	if (position && position.x && position.y) {
		const scaledPosition = {
			x: position.x / scaleFactor,
			y: position.y / scaleFactor,
		};
		win.setPosition(scaledPosition.x, scaledPosition.y);
	}

### Expected Behavior

Place the Window on another Monitor with another ScaleFactor than 100% and it should stay at the same window size after a restart.

### Steps To Reproduce

Place App on another Monitor with a non normal ScaleFactor
Close APP
Open APP

### YTMDesktop

v2 RC-2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

exe

**Comment by NovusTheory** [comment]
The commit above should correct scaling issues

**Comment by Sickjuicy** [comment]
How can I test it, because if I download the v2 branch and try it with yarn (yarn install, yarn start) i get an error

**Comment by Sickjuicy** [comment]
.

**Comment by Alipoodle** [comment]
> How can I test it, because if I download the v2 branch and try it with yarn (yarn install, yarn start) i get an error

Could you share?

**Comment by Sickjuicy** [comment]
```

E:\YT-musc-Dev-Test\ahh\ytmdesktop-2>yarn make
yarn run v1.22.19
$ electron-forge make
√ Checking your system
\ Loading configuration
× Loading configuration
  › Cannot find module 'electron-winstaller'
  Require stack:
  - E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\@elec…
■ Resolving make targets
■ Running package command
■ Running preMake hook
■ Making distributables
■ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Cannot find module 'electron-winstaller'
Require stack:
- E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\@electron-forge\maker-squirrel\dist\MakerSquirrel.js
- E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\forge.config.ts
- E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\@electron-forge\core\dist\util\forge-config.js
- E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\@electron-forge\core\dist\util\index.js
- E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\@electron-forge\core\dist\api\index.js
- E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\@electron-forge\cli\dist\electron-forge-make.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\@electron-forge\maker-squirrel\src\MakerSquirrel.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\forge.config.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (E:\YT-musc-Dev-Test\ahh\ytmdesktop-2\node_modules\ts-node\src\index.ts:1618:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Alipoodle** [comment]
Did you just download the ZIP 😅?
It's reporting it's not a Git Repo (and why both of the husky and Electron make are complaining)

Strange that `electron-wininstaller` is missing

**Comment by Sickjuicy** [comment]
emmmm yes I did xD ....
I managed to make it work that I can use yarn start and there the fix works.
But I have a problem to make myself a build. I think it is because I have windows 11 and "only" x64

I 
```
E:\YT-musc-Dev-Test\ahh\asd\ytmdesktop>yarn make
yarn run v1.22.19
$ electron-forge make
√ Checking your system
√ Loading configuration
√ Resolving make targets
  › Making for the following targets: squirrel
> Running package command
√ Loading configuration
√ Resolving make targets
  › Making for the following targets: squirrel
> Running package command
  √ Preparing to package application
  √ Running packaging hooks
    √ Running generateAssets hook
    √ Running prePackage hook
      √ [plugin-webpack] Preparing native dependencies: 1 / 1
      √ [plugin-webpack] Building webpack bundles
  √ Packaging application
    √ Packaging for ia32 on win32 [4s]
  > Running postPackage hook
    / [plugin-electronegativity] Running postPackage hook
■ Running preMake hook
■ Making distributables
■ Running postMake hook
Releases list is up to date.
Unknown Electron release "26.1.x", please check manually for available security fixes.
┌─────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬──────────────────────────────────────────────────┐
│ Check ID                                │ Affected File
                               │ Location │ Issue Description                                │
├─────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ AVAILABLE_SECURITY_FIXES_GLOBAL_CHECK   │ E:\YT-musc-Dev-Test\ahh\asd\ytmdesktop\out\YouTube Music Desktop App-win32-ia32\resources\app\package.json │ 0:0      │ https://git.io/Jeu1X                             │
│ *Review Required*                       │
                               │          │                                                  │
│ INFORMATIONAL | TENTATIVE               │
                               │          │                                                  │
├─────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ CSP_GLOBAL_CHECK                        │ N/A
                               │ 0:0      │ https://git.io/JeuMe                             │
│ MEDIUM | CERTAIN                        │
                               │          │                                                  │
├─────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ LIMIT_NAVIGATION_GLOBAL_CHECK           │ N/A
                               │ 0:0      │ https://git.io/JeuMs                             │
│ HIGH | CERTAIN                          │
√ Loading configuration
√ Resolving make targets
  › Making for the following targets: squirrel
√ Running package command
  √ Preparing to package application
  √ Running packaging hooks
    √ Running generateAssets hook
    √ Running prePackage hook
      √ [plugin-webpack] Preparing native dependencies: 1 / 1
      √ [plugin-webpack] Building webpack bundles
  √ Packaging application
    √ Packaging for ia32 on win32 [4s]
  √ Running postPackage hook
    √ [plugin-electronegativity] Running postPackage hook
√ Running preMake hook
> Making distributables
  × Making a squirrel distributable for win32/ia32
    › Failed with exit code: 4294967295
    Output:
    System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---…
      bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
      bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
      bei Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
      --- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
      bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      bei Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
      --- Ende der internen Ausnahmestapel�berwachung ---
      bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
      bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
      bei Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotes…
      bei Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapper…
      bei Squirrel.Update.Program.executeCommandLine(String[] args)
      bei Squirrel.Update.Program.main(String[] args)
      bei Squirrel.Update.Program.Main(String[] args)
      ---> (Interne Ausnahme #0) System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Da…
      bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
      bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
      bei Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
      --- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
      bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      bei Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---
■ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Failed with exit code: 4294967295
Output:
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ComponentModel.Win32Exception: Das System kann die angegebene Datei nicht finden
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
   --- Ende der internen Ausnahmestapel�berwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   bei Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   bei Squirrel.Update.Program.executeCommandLine(String[] args)
   bei Squirrel.Update.Program.main(String[] args)
   bei Squirrel.Update.Program.Main(String[] args)
---> (Interne Ausnahme #0) System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Datei nicht finden
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---
at ChildProcess.<anonymous> (E:\YT-musc-Dev-Test\ahh\asd\ytmdesktop\node_modules\electron-winstaller\src\spawn-promise.ts:52:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Alipoodle** [comment]
>  I have windows 11 and "only" x64
This is shouldn't be an issue, Electron 23 and above can only compile to x64 as they removed support for older versions of Windows in about Chromium 90~.

Will take a look at the error at work, and discuss how we can properly fix the issues with no Git repo for at least building

**Comment by Sickjuicy** [comment]
I would just put the git clone comment with the v2 branch selected in the installation guide. I used it the last time, with the current error

**Comment by Alipoodle** [comment]
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/a9897d1e-225a-4f5a-81ba-82b9b99a0e3a)
We do specify this before. 🤷 

I personally think we should try and add a catch in for if you download via Source ZIP.😅
But we're missing the info we use in the settings screen for that is VERY Helpful for us when it comes to debugging...
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/24062521-103f-4b55-b459-7c55608c0a28)

**Comment by Alipoodle** [comment]
2 things to say:

1) First of all I'm working on adding a patch for the Making of YTM Desktop to throw a proper error when no Git Repo is there describing for users to clone the repo from us instead.

2) I think there's some wrong information in here.
> Arch: x64

> √ Packaging for ia32 on win32

Could I ask what CPU you are running?
As I suspect that this is building for a 32bit CPU rather than 64bit 😵

**Comment by Sickjuicy** [comment]
I have a Ryzen 9 3900X

**Comment by Alipoodle** [comment]
Could you see if running: `yarn make --arch=x64` works for you?
Strangely it seems Electron-forge is presuming you are running 32 bit instead?!

**Comment by Sickjuicy** [comment]
```
E:\YT-musc-Dev-Test\ahh\asd\ytmdesktop>yarn make --arch=x64
yarn run v1.22.19
$ electron-forge make --arch=x64
√ Checking your system
√ Loading configuration
√ Resolving make targets
  › Making for the following targets: squirrel
> Running package command
√ Loading configuration
√ Resolving make targets
  › Making for the following targets: squirrel
> Running package command
  √ Preparing to package application
  √ Running packaging hooks
    √ Running generateAssets hook
    √ Running prePackage hook
      √ [plugin-webpack] Preparing native dependencies: 1 / 1
      √ [plugin-webpack] Building webpack bundles
  √ Packaging application
    √ Packaging for x64 on win32 [6s]
  > Running postPackage hook
    \ [plugin-electronegativity] Running postPackage hook
■ Running preMake hook
■ Making distributables
■ Running postMake hook
Releases list is up to date.
Unknown Electron release "26.1.x", please check manually for available security fixes.
┌─────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────┬──────────────────────────────────────────────────┐
│ Check ID                                │ Affected File                                                                                             │ Location │ Issue Description                                │
├─────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ AVAILABLE_SECURITY_FIXES_GLOBAL_CHECK   │ E:\YT-musc-Dev-Test\ahh\asd\ytmdesktop\out\YouTube Music Desktop App-win32-x64\resources\app\package.json │ 0:0      │ https://git.io/Jeu1X                             │
│ *Review Required*                       │                                                                                                           │          │                                                  │
│ INFORMATIONAL | TENTATIVE               │                                                                                                           │          │                                                  │
├─────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ CSP_GLOBAL_CHECK                        │ N/A                                                                                                       │ 0:0      │ https://git.io/JeuMe                             │
│ MEDIUM | CERTAIN                        │                                                                                                           │          │                                                  │
├─────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────┼──────────────────────────────────────────────────┤
│ LIMIT_NAVIGATION_GLOBAL_CHECK           │ N/A                                                                                                       │ 0:0      │ https://git.io/JeuMs                             │
│ HIGH | CERTAIN                          │                                                                             √ Loading configuration
√ Resolving make targets
  › Making for the following targets: squirrel
√ Running package command
  √ Preparing to package application
  √ Running packaging hooks
    √ Running generateAssets hook
    √ Running prePackage hook
      √ [plugin-webpack] Preparing native dependencies: 1 / 1
      √ [plugin-webpack] Building webpack bundles
  √ Packaging application
    √ Packaging for x64 on win32 [6s]
  √ Running postPackage hook
    √ [plugin-electronegativity] Running postPackage hook
√ Running preMake hook
> Making distributables
  × Making a squirrel distributable for win32/x64
    › Failed with exit code: 4294967295
    Output:
    System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---…
      bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
      bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
      bei Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
      --- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
      bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      bei Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
      --- Ende der internen Ausnahmestapel�berwachung ---
      bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
      bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
      bei Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotes…
      bei Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapper…
      bei Squirrel.Update.Program.executeCommandLine(String[] args)
      bei Squirrel.Update.Program.main(String[] args)
      bei Squirrel.Update.Program.Main(String[] args)
      ---> (Interne Ausnahme #0) System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Da…
      bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
      bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
      bei Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
      --- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
      bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      bei Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---
■ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Failed with exit code: 4294967295
Output:
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ComponentModel.Win32Exception: Das System kann die angegebene Datei nicht finden
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
   --- Ende der internen Ausnahmestapel�berwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   bei Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   bei Squirrel.Update.Program.executeCommandLine(String[] args)
   bei Squirrel.Update.Program.main(String[] args)
   bei Squirrel.Update.Program.Main(String[] args)
---> (Interne Ausnahme #0) System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Datei nicht finden
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- Ende der Stapel�berwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel�st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---
at ChildProcess.<anonymous> (E:\YT-musc-Dev-Test\ahh\asd\ytmdesktop\node_modules\electron-winstaller\src\spawn-promise.ts:52:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Alipoodle** [comment]
Given the errors are in German rather than english, I can't see any notiable errors error messages to know what happened.

From things like electron-winstaller not being installed and it assuming you're on a 32bit processor provides me with the main belief that this is the cause of the problem.
Unsure as to how those might have happened though.

**Comment by Sickjuicy** [comment]
In the test I installed electron-winstaller and the german error says that it could not find a file after that System.ComponentModel.Win32Exception

**Comment by NovusTheory** [comment]
Closing as this is in the rc.3 published release. Discussion can still take place here for what was going on previously

**Comment by Sickjuicy** [comment]
Hey I now know why I cant build, because I used on a x64 build an x32 installation of node, because of that I had the ia32 arch, now i have the x64 version installed I have no problems.
