### ISSUE TITLE
Crash on shuffling my likes

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#1164]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I pressed Shuffle on "my likes" playlist and got

YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.2
    Electron 26.1.0
    Windows NT 10.0.22621

Name: TypeError
Message: e is not iterable
Cause: Unknown

TypeError: e is not iterable
    at o (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc2\resources\app\.webpack\main\index.js:8:721326)
    at c (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc2\resources\app\.webpack\main\index.js:8:721575)
    at d (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc2\resources\app\.webpack\main\index.js:8:721960)
    at Array.map (<anonymous>)
    at Object.updateQueue (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc2\resources\app\.webpack\main\index.js:8:723667)
    at IpcMainImpl.<anonymous> (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc2\resources\app\.webpack\main\index.js:8:688148)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88940)
    at WebContents.emit (node:events:513:28)

### Expected Behavior

Playing music

### Steps To Reproduce

My likes playlist, press shuffle

### YTMDesktop

2.0rc2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

exe

**Comment by Deanosim** [comment]
I appear to have the exact same error, but mine happens when launching YouTube Music Desktop, it just spits out the error and forces me to close the app. 

```log
YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.3
    Electron 26.2.1
    Windows NT 10.0.22621

Name: TypeError
Message: e is not iterable
Cause: Unknown

TypeError: e is not iterable
    at o (C:\Users\Deano\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:721975)
    at c (C:\Users\Deano\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:722224)
    at l (C:\Users\Deano\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:722079)
    at Array.map (<anonymous>)
    at c (C:\Users\Deano\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:722335)
    at d (C:\Users\Deano\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:722609)
    at Array.map (<anonymous>)
    at Object.updateQueue (C:\Users\Deano\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:724316)
    at IpcMainImpl.<anonymous> (C:\Users\Deano\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:687400)
    at IpcMainImpl.emit (node:events:513:28)
```

**Comment by Alipoodle** [comment]
This issue is fixed in the v2 Branch however a new release has not been made yet 😁
We plan to push out a new release in the coming days, so please wait before the fix is in the latest build.

**Comment by NovusTheory** [comment]
Closing as this is part of rc.4 release
