### ISSUE TITLE
Unable to bind multimedia buttons to v2 shortcuts

### ISSUE THREAD

**Issue by Sollaze** [ytmdesktop/ytmdesktop#1171]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Trying to set multimedia buttons of a keyboard as shortcuts in the new version of the app is not supported and will simply leave the selection as it is.

### Expected Behavior

Able to exclusively bind multimedia buttons to the app so Windows doesn't decide to pause/skip/etc. other playing media when trying to control YTMD.

### Steps To Reproduce

1. Go to Settings/Shortcuts
2. Attempt to bind multimedia keyboard key
3. Fail

### YTMDesktop

2.0.0-rc.3

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by NovusTheory** [comment]
Multimedia buttons are explicitly declined to be set as global shortcuts because they are already bound by the media service from the operating system. Unfortunately it seems like the way YTM works it constantly unregisters itself as a media source anytime a new song is played so that leads to constantly having to switch the active media in Windows so the buttons control that one. We can take a look into how this can be mitigated.

**Comment by NovusTheory** [comment]
If you don't like to use the operating systems media service you can append `--disable-features=MediaSessionService` to the shortcut for YTMD. This does disable the hardware media keys from being used for YTMD but it removes the popup that you do not like

**Comment by Sollaze** [comment]
Well I should clarify that using the keys to actually control YTMD is still more important than not seeing the popup. It's the main reason I bought a keyboard with them in the first place haha

**Comment by NovusTheory** [comment]
A current workaround could be to manually edit your config file to set shortcuts to `MediaPlayPause` `MediaTrackPrevious` and `MediaTrackNext` and see if that works as we only disallow it in the settings window but config.json is fair game. Pair this with disabling the MediaSessionService and you'll likely get the functionality you had before back. No guarantees this will stay working in later versions though hopefully by then this issue would be resolved

**Comment by Sollaze** [comment]
Even without disabling the `MediaSessionService`, binding `playPause` to `MediaPlayPause` worked as I had hoped but binding other controls to `MediaTrackNext` and/or `MediaTrackPrevious` both crash the app with the following error:
```
YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.3
    Electron 26.2.1
    Windows NT 10.0.19045

Name: TypeError
Message: Error processing argument at index 0, conversion failure from MediaTrackNext
Cause: Unknown

TypeError: Error processing argument at index 0, conversion failure from MediaTrackNext
    at B (C:\Users\[radacted]\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:676331)
    at App.<anonymous> (C:\Users\[radacted]\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:688822)
    at App.emit (node:events:513:28)
```

**Comment by NovusTheory** [comment]
Hmm those keys might have some other problems associated with them when being set then. Currently that is under a "won't fix" while this issue is discussed internally with how to handle the media service and hardware media keys

**Comment by NovusTheory** [comment]
Update: Try `MediaNextTrack` and `MediaPreviousTrack`. The actual key names don't line up with what would be registered for a shortcut

**Comment by Sollaze** [comment]
Works perfectly fine! Same behavior as on older versions.

**Comment by hustinjinx** [comment]
> A current workaround could be to manually edit your config file to set shortcuts to `MediaPlayPause` `MediaTrackPrevious` and `MediaTrackNext` and see if that works as we only disallow it in the settings window but config.json is fair game. Pair this with disabling the MediaSessionService and you'll likely get the functionality you had before back. No guarantees this will stay working in later versions though hopefully by then this issue would be resolved

Is this no longer an option in 2.0.1? I can't control the app with media controls and I see no where in the app-2.0.1 for a config file.

**Comment by hustinjinx** [comment]
> > > A current workaround could be to manually edit your config file to set shortcuts to `MediaPlayPause` `MediaTrackPrevious` and `MediaTrackNext` and see if that works as we only disallow it in the settings window but config.json is fair game. Pair this with disabling the MediaSessionService and you'll likely get the functionality you had before back. No guarantees this will stay working in later versions though hopefully by then this issue would be resolved
> > 
> > 
> > Is this no longer an option in 2.0.1? I can't control the app with media controls and I see no where in the app-2.0.1 for a config file.
> 
> @hustinjinx It's still an option. You'll find the config file here: `%appdata%\YouTube Music Desktop App\config.json`
> 
> Then you can just replace the values for `playPause`, `next`, and `previous` with `MediaPlayPause`, `MediaNextTrack`, and `MediaPreviousTrack` respectively.

That worked, thank you!! I couIdn't find it but found it in %appdata%\Roaming\YouTube Music Desktop App\

**Comment by Sollaze** [comment]
Odd, `%appdata%` should take you directly to the Roaming folder. But whatever glad it worked!
