### ISSUE TITLE
App crash upon file rename

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#1199]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Error after resuming PC from standby

YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.5
    Electron 27.0.2
    Windows NT 10.0.22621

Name: Error
Message: EPERM: operation not permitted, rename 'C:\Users\dario.piantanida\AppData\Roaming\YouTube Music Desktop App\config.json.tmp-9629608708fd2873' -> 'C:\Users\dario.piantanida\AppData\Roaming\YouTube Music Desktop App\config.json'
Cause: Unknown

Error: EPERM: operation not permitted, rename 'C:\Users\dario.piantanida\AppData\Roaming\YouTube Music Desktop App\config.json.tmp-9629608708fd2873' -> 'C:\Users\dario.piantanida\AppData\Roaming\YouTube Music Desktop App\config.json'
    at renameSync (node:fs:1042:3)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47398)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47472)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47472)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47472)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47472)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47472)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47472)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47472)
    at n (C:\Users\dario.piantanida\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:47472)

### Expected Behavior

No errors

### Steps To Reproduce

Resume from standby, maybe

### YTMDesktop

2.0.0-rc.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

EXE

**Comment by NovusTheory** [comment]
This should be fixed when upstream dependency releases are pushed. We cannot utilize a version of a dependency we have yet that should alleviate this issue as it uses ESM.

**Comment by ethan-conrad1** [comment]
@NovusTheory Are there any updates on this one at all? Still remains a problem for me

**Comment by NovusTheory** [comment]
> Are there any updates on this one at all? Still remains a problem for me

@ethan-conrad1 The application still hasn't been moved to ESM. It is planned but it's not a simple task as it requires all dependencies to be ESM compatible.
