### ISSUE TITLE
Yarn install fails on Gentoo 

### ISSUE THREAD

**Issue by ZoeArch** [ytmdesktop/ytmdesktop#1239]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

yarn install register-scheme fails with exit code 1

terminal output:

```yarn install
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > discord-rpc@3.1.4" has incorrect peer dependency "register-scheme@github:devsnek/node-register-scheme".
[4/4] Building fresh packages...
[10/14] ⠈ @nodert-win10-rs4/windows.foundation
[7/14] ⠈ electron
[6/14] ⠈ electron
[4/14] ⠈ register-scheme
error /home/zoe/gitstuff/ytmdesktop/node_modules/register-scheme: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/zoe/gitstuff/ytmdesktop/node_modules/register-scheme
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.9.0 | linux | x64
gyp info find Python using Python version 3.11.7 found at "/usr/lib/python-exec/python3.11/python3"

gyp info spawn /usr/lib/python-exec/python3.11/python3
gyp info spawn args [
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/register-scheme/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.cache/node-gyp/20.9.0/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/zoe/.cache/node-gyp/20.9.0',
gyp info spawn args '-Dnode_gyp_dir=/home/zoe/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/zoe/.cache/node-gyp/20.9.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/zoe/gitstuff/ytmdesktop/node_modules/register-scheme',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: /home/zoe/.cache/node-gyp/20.9.0/common.gypi not found (cwd: /home/zoe/gitstuff/ytmdesktop/node_modules/register-scheme) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/zoe/.config/yarn/global/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:514:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.6.13-gentoo-dist
gyp ERR! command "/usr/bin/node" "/home/zoe/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/zoe/gitstuff/ytmdesktop/node_modules/register-scheme




warning Error running install script for optional dependency: "/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.foundation: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.foundation
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.9.0 | linux | x64
gyp info find Python using Python version 3.11.7 found at \"/usr/lib/python-exec/python3.11/python3\"

gyp info spawn /usr/lib/python-exec/python3.11/python3
gyp info spawn args [
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.foundation/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.foundation/common.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.cache/node-gyp/20.9.0/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/zoe/.cache/node-gyp/20.9.0',
gyp info spawn args '-Dnode_gyp_dir=/home/zoe/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/zoe/.cache/node-gyp/20.9.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.foundation',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: /home/zoe/.cache/node-gyp/20.9.0/common.gypi not found (cwd: /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.foundation) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/zoe/.config/yarn/global/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:514:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.6.13-gentoo-dist
gyp ERR! command \"/usr/bin/node\" \"/home/zoe/.yarn/bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.foundation
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.media: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.media
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.9.0 | linux | x64
gyp info find Python using Python version 3.11.7 found at \"/usr/lib/python-exec/python3.11/python3\"

gyp info spawn /usr/lib/python-exec/python3.11/python3
gyp info spawn args [
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.media/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.media/common.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.cache/node-gyp/20.9.0/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/zoe/.cache/node-gyp/20.9.0',
gyp info spawn args '-Dnode_gyp_dir=/home/zoe/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/zoe/.cache/node-gyp/20.9.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.media',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: /home/zoe/.cache/node-gyp/20.9.0/common.gypi not found (cwd: /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.media) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/zoe/.config/yarn/global/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:514:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.6.13-gentoo-dist
gyp ERR! command \"/usr/bin/node\" \"/home/zoe/.yarn/bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.media
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.storage.streams: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.storage.streams
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.9.0 | linux | x64
gyp info find Python using Python version 3.11.7 found at \"/usr/lib/python-exec/python3.11/python3\"

gyp info spawn /usr/lib/python-exec/python3.11/python3
gyp info spawn args [
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.storage.streams/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.storage.streams/common.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.cache/node-gyp/20.9.0/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/zoe/.cache/node-gyp/20.9.0',
gyp info spawn args '-Dnode_gyp_dir=/home/zoe/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/zoe/.cache/node-gyp/20.9.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.storage.streams',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: /home/zoe/.cache/node-gyp/20.9.0/common.gypi not found (cwd: /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.storage.streams) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/zoe/.config/yarn/global/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:514:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.6.13-gentoo-dist
gyp ERR! command \"/usr/bin/node\" \"/home/zoe/.yarn/bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/zoe/gitstuff/ytmdesktop/node_modules/@nodert-win10-rs4/windows.storage.streams
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/home/zoe/gitstuff/ytmdesktop/node_modules/abstract-socket: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/zoe/gitstuff/ytmdesktop/node_modules/abstract-socket
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.9.0 | linux | x64
gyp info find Python using Python version 3.11.7 found at \"/usr/lib/python-exec/python3.11/python3\"

gyp info spawn /usr/lib/python-exec/python3.11/python3
gyp info spawn args [
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/abstract-socket/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.cache/node-gyp/20.9.0/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/zoe/.cache/node-gyp/20.9.0',
gyp info spawn args '-Dnode_gyp_dir=/home/zoe/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/zoe/.cache/node-gyp/20.9.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/zoe/gitstuff/ytmdesktop/node_modules/abstract-socket',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: /home/zoe/.cache/node-gyp/20.9.0/common.gypi not found (cwd: /home/zoe/gitstuff/ytmdesktop/node_modules/abstract-socket) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/zoe/.config/yarn/global/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:514:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.6.13-gentoo-dist
gyp ERR! command \"/usr/bin/node\" \"/home/zoe/.yarn/bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/zoe/gitstuff/ytmdesktop/node_modules/abstract-socket
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/home/zoe/gitstuff/ytmdesktop/node_modules/windows.media.playback: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/zoe/gitstuff/ytmdesktop/node_modules/windows.media.playback
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.9.0 | linux | x64
gyp info find Python using Python version 3.11.7 found at \"/usr/lib/python-exec/python3.11/python3\"

gyp info spawn /usr/lib/python-exec/python3.11/python3
gyp info spawn args [
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/windows.media.playback/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/gitstuff/ytmdesktop/node_modules/windows.media.playback/common.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/zoe/.cache/node-gyp/20.9.0/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/zoe/.cache/node-gyp/20.9.0',
gyp info spawn args '-Dnode_gyp_dir=/home/zoe/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/zoe/.cache/node-gyp/20.9.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/zoe/gitstuff/ytmdesktop/node_modules/windows.media.playback',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: /home/zoe/.cache/node-gyp/20.9.0/common.gypi not found (cwd: /home/zoe/gitstuff/ytmdesktop/node_modules/windows.media.playback) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/zoe/.config/yarn/global/node_modules/node-gyp/lib/configure.js:271:18)
gyp ERR! stack at ChildProcess.emit (node:events:514:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Linux 6.6.13-gentoo-dist
gyp ERR! command \"/usr/bin/node\" \"/home/zoe/.yarn/bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/zoe/gitstuff/ytmdesktop/node_modules/windows.media.playback
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```

### Expected Behavior

yarn install runs successfully

### Steps To Reproduce

follow the build instructions:

1. clone the repository
2. enter repository directory
3. run yarn install
4. error occurs

### YTMDesktop

Master Branch as of 2024-01-20 18:20 GMT+0

### OS

Gentoo

### OS Version

N/A

### Arch

x64

### Installation way

build

**Comment by Alipoodle** [comment]
It appears to be trying to build some Windows specifically libraries.

I would more recommend trying the V2 branch instead as this is more up to date and better development in comparison.
It does lack a few features like MPRIS in it.

**Comment by ZoeArch** [comment]
this worked, thank you
