### ISSUE TITLE
V2: Creating a Shortcut of "CTRL + Pause" will crash the app

### ISSUE THREAD

**Issue by Mackamuir** [ytmdesktop/ytmdesktop#1241]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Creating a keybind that combines Control + Pause will hardcrash the app and prevent it from relaunching without changing the app config manually

### Expected Behavior

It not do that

### Steps To Reproduce

YTMD Settings > Shortcuts > set a shortcut of "Ctrl + Pause"

To resolve:
go to `%appdata%\YouTube Music Desktop App\config.json` and remove the line of `CmdOrCtrl+Cancel`

### YTMDesktop

2.0.0-rc.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

```
YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.5
    Electron 27.0.2
    Windows NT 10.0.22621

Name: TypeError
Message: Error processing argument at index 0, conversion failure from CmdOrCtrl+Cancel
Cause: Unknown

TypeError: Error processing argument at index 0, conversion failure from CmdOrCtrl+Cancel
    at G (C:\Users\macka\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:498184)
    at e.exports.<anonymous> (C:\Users\macka\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:505857)
    at EventEmitter.n (C:\Users\macka\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:68841)
    at EventEmitter.emit (node:events:526:35)
    at set store [as store] (C:\Users\macka\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:68132)
    at e.exports.set (C:\Users\macka\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:66860)
    at IpcMainImpl.<anonymous> (C:\Users\macka\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:515912)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88262)
    at WebContents.emit (node:events:514:28)
```

**Comment by Mackamuir** [comment]
Duplicate of a million other issues already opened. closed.
