### ISSUE TITLE
Using + as a shortcut for volume up crashes the app

### ISSUE THREAD

**Issue by manuti** [ytmdesktop/ytmdesktop#1293]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I'm setting the shortcuts and everything is going OK till a select + as volume up. The app crashes and refuse to start again. 

### Expected Behavior

If + is forbidden avoid select as a shortcut, in any case left + as volume up.

### Steps To Reproduce

1. Go to settings
2. Go to shortcuts
3. select + as Volume up

### YTMDesktop

v2.0.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

The log when I try to restart the app:
YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0
    Electron 28.2.0
    Windows NT 10.0.22621

Name: TypeError
Message: Error processing argument at index 0, conversion failure from +
Cause: Unknown

TypeError: Error processing argument at index 0, conversion failure from +
    at X (C:\Users\MRJ\AppData\Local\youtube_music_desktop_app\app-2.0.0\resources\app.asar\.webpack\main\index.js:8:407192)
    at App.<anonymous> (C:\Users\MRJ\AppData\Local\youtube_music_desktop_app\app-2.0.0\resources\app.asar\.webpack\main\index.js:8:429100)

**Comment by manuti** [comment]
I manually edit config.json in %%AppData%%\Roaming\YouTube Music Desktop App and remove the "+". Now the app restart correctly.

**Comment by manuti** [comment]
Sorry for duplicating this. I try different search before the issue rise but I did not find.

**Comment by manuti** [comment]
> Duplicate of #1281

Sorry for duplicating this. I try different search before the issue rise but I did not find.
