### ISSUE TITLE
'YouTube Music is taking longer than usual to load' when signed in

### ISSUE THREAD

**Issue by LooFifteen** [ytmdesktop/ytmdesktop#1340]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The application never loads and is stuck in the loading menu. After clearing all the data, it loads once again. After signing in, the app no longer loads again.
![youtube-music-desktop-app_dMA5kKPCcB](https://github.com/ytmdesktop/ytmdesktop/assets/39528861/2d0360ac-aefc-4b29-9dd4-c62783b709be)

### Expected Behavior

I'd assume that the app is supposed to load when signed in.

### Steps To Reproduce

1. Launch application
2. It doesn't load
3. Clear data
4. It loads

### YTMDesktop

v2.0.1

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

```
[2024-02-27 17:31:49.159][renderer][error] requestStorageAccessFor: Permission denied.
[2024-02-27 17:31:54.246][main][error] Electron event App#child-process-gone observed {
  type: 'Utility',
  reason: 'killed',
  exitCode: 1,
  serviceName: 'network.mojom.NetworkService',
  name: 'Network Service'
}
[2024-02-27 17:31:54.251][main][error] Electron event App#render-process-gone observed {
  reason: 'killed',
  exitCode: 1,
  webContents: {
    id: 1,
    url: 'file:///C:/Users/Luis/AppData/Local/youtube_music_desktop_app/app-2.0.1/resources/app.asar/.webpack/renderer/main_window/index.html'
  }
}
[2024-02-27 17:31:54.256][main][error] Electron event App#render-process-gone observed {
  reason: 'killed',
  exitCode: 1,
  webContents: { id: 2, url: 'https://music.youtube.com/' }
}
[2024-02-27 17:31:54.270][main][error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:83002)
    at _.send (node:electron/js2c/browser_init:2:69166)
    at EventEmitter.<anonymous> (C:\Users\Luis\AppData\Local\youtube_music_desktop_app\app-2.0.1\resources\app.asar\.webpack\main\index.js:8:390812)
    at EventEmitter.emit (node:events:517:28)
    at t.default.set (C:\Users\Luis\AppData\Local\youtube_music_desktop_app\app-2.0.1\resources\app.asar\.webpack\main\index.js:8:459080)
    at ie (C:\Users\Luis\AppData\Local\youtube_music_desktop_app\app-2.0.1\resources\app.asar\.webpack\main\index.js:8:403823)
    at WebContents.<anonymous> (C:\Users\Luis\AppData\Local\youtube_music_desktop_app\app-2.0.1\resources\app.asar\.webpack\main\index.js:8:405290)
    at WebContents.emit (node:events:529:35)
```

**Comment by jintei** [comment]
Until yesterday it was working fine for me, now the app doesn't load if you reopen it after logging in. Didn't happen on earlier builds (1.x.x)

**Comment by NovusTheory** [comment]
Does this still happen in v2.0.2?

**Comment by LooFifteen** [comment]
Seems to have fixed it, thank you!

**Comment by jintei** [comment]
Thanks for the fix !!
