### ISSUE TITLE
JavaScript Error on Mac version

### ISSUE THREAD

**Issue by paperplanefactory** [ytmdesktop/ytmdesktop#363]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Uncaught Exception:
TypeError: Cannot read property 'NowPlaying' of undefined
    at Object.updateNowPlaying (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/src/providers/scrobblerProvider.js:88:15)
    at updateActivity (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/main.js:429:43)
    at Timeout._onTimeout (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/main.js:340:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**To Reproduce**
Play a son and after a while the messge will popup and interrupt the song

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: 1.12.1 (1.12.1)
 * OS: Mac
 * OS version: 10.15.6 (19G2021)
 * Arch: x86
* Installation way: x86 DMG

**Comment by Fusion** [comment]
I would like to add that I am seeing the same error in Windows 10 so it's not a Mac error _per se_.

**Comment by wubli** [comment]
![image](https://user-images.githubusercontent.com/14149143/101545389-7a5a6c00-39a7-11eb-8272-64322fdd713a.png)
Windows 10

**Comment by Fusion** [comment]
So, I decided to take a quick look at the source code and felt like an idiot.
Turns out, Scrobbler is last.fm's integration.
Thus, either disable the Last FM integration in the settings or enter your account information and authorize it.
Agreed, this error could be handled a bit better but there's a dose of user error in there as well :)

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
