### ISSUE TITLE
Uncaught exception: Failed to serialize arguments

### ISSUE THREAD

**Issue by colindean** [ytmdesktop/ytmdesktop#516]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**

After launching, on next track change, I see this error:

```
Uncaught Exception:
Error: Failed to serialize arguments
    at WebContents._.send (electron/js2c/browser_init.js:157:2252)
    at sendMsg (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/node_modules/electron-native-notification/index.js:49:46)
    at BrowserWindow.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/node_modules/electron-native-notification/index.js:55:40)
    at BrowserWindow.emit (events.js:322:22)
```

I don't see notifications even though I've it enabled.

**To Reproduce**

1. Start music
2. Wait for track change

**Expected behavior**

1. No error dialogs
2. Notifications showing on track change

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Mac***
 * OS version: ***10.15.7***
 * Arch: ***amd64***
* Installation way: Homebrew Cask: `brew cask install ytmdesktop`

**Comment by georgeherby** [comment]
I got this when upgrading from 1.9.0 to 1.13.0

**Comment by aaronflorey** [comment]
I just installed the AppImage for Ubuntu 20.10 and also get this error

**Comment by Sensei1304** [comment]
Also got this issue with snap package at  Debian 10 (version 1.13.0)

**Comment by Bewbman** [comment]
![Youtube Music Bug](https://user-images.githubusercontent.com/16722630/102561566-0d2f9080-40a3-11eb-8953-46503b6515c1.png)
Figured this could help, this is what I get.

**Comment by Brog33** [comment]
I am getting this too.

Ubuntu 20.04, Snap package. 1.13.0

**Comment by leonbohmann** [comment]
Same here on Windows with 1.13.0.

**Comment by Myvillithdar** [comment]
I'm also getting this error on Arch Linux, version 1.13.0-3 from the AUR

**Comment by mkunkel** [comment]
Same here
Ubuntu 18.04.3, Snap package. 1.13.0
