### ISSUE TITLE
Fail to build application or AUR package

### ISSUE THREAD

**Issue by MarkoShiva** [ytmdesktop/ytmdesktop#80]
I get the same error when trying installing AUR package on Archlinux or trying building locally.
Error is about node-gyp
Terminal output added if you need log output also I can provide that too.

```
 $ npm install

> husky@3.1.0 install /home/markopavlovic/git/ytmdesktop/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> register-scheme@0.0.2 install /home/markopavlovic/git/ytmdesktop/node_modules/register-scheme
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Class constructor Range cannot be invoked without 'new'
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/node-gyp/lib/find-python.js:229:28)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/node-gyp/lib/find-python.js:274:7)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:293:7)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
gyp ERR! System Linux 5.3.13-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/markopavlovic/git/ytmdesktop/node_modules/register-scheme
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! register-scheme@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the register-scheme@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/markopavlovic/.npm/_logs/2019-12-28T19_05_30_439Z-debug.log
```

**Comment by MarkoShiva** [comment]
log is large almost 12000 lines so I paste it via link https://dpaste.org/NcsB

**Comment by MarkoShiva** [comment]
@adlerluiz Btw very decent and nice looking app. Really remind on the youtube music mobile app. 
I tried with appimage which works but I guess you have some problems installation or there are some requirements that are not written for installation.

**Comment by adlerluiz** [comment]
Hello @MarkoShiva thank you.

Could you try with the latest lts version of node? I saw that you are using v13.

**Comment by adlerluiz** [comment]
You can see too

https://aur.archlinux.org/packages/ytmdesktop-git

**Comment by rickinbsb** [comment]
@garfunkel do you have some insight on this?

**Comment by garfunkel** [comment]
I am able to reproduce this.

I updated the AUR package to reflect the newer 1.7.0 release. Same issue presents there also.

The issue occurs when running npm install. The error is also produced when following the build/setup instructions on the readme, so that rules out the AUR build scripts being the culprit.

npm version 6.13.4
node version v13.5.0

There might be a problem here with Arch's version of NPM/Node and ytmdesktop.

**Comment by garfunkel** [comment]
This might be relevent: https://github.com/zeit/next.js/issues/8973

Unfortunately I'm not much of a NPM/Node person...

**Comment by rickinbsb** [comment]
thanks! I'll have a look

**Comment by garfunkel** [comment]
Either 1.8.0, or something in Arch has resulted in this error now being replaced with:

```
> husky@3.1.0 install /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> register-scheme@0.0.2 install /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/register-scheme
> node-gyp rebuild

make: Entering directory '/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/register-scheme/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/register-protocol-handler/src/addon.o
  CXX(target) Release/obj.target/register-protocol-handler/src/register_linux.o
  SOLINK_MODULE(target) Release/obj.target/register-protocol-handler.node
  COPY Release/register-protocol-handler.node
make: Leaving directory '/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/register-scheme/build'

> core-js@3.6.1 postinstall /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> protobufjs@6.8.8 postinstall /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/protobufjs
> node scripts/postinstall


> electron@7.1.7 postinstall /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/electron
> node install.js


> husky@3.1.0 postinstall /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

added 959 packages from 933 contributors and audited 3914 packages in 9.873s

6 packages are looking for funding
  run `npm fund` for details

found 53 vulnerabilities (10 low, 27 moderate, 16 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> youtube-music-desktop-app@1.8.0 pack:x64 /home/simon/ytmdesktop-git/src/ytmdesktop
> npm run pack -- --arch x64 --config electron-builder64.yml


> youtube-music-desktop-app@1.8.0 pack /home/simon/ytmdesktop-git/src/ytmdesktop
> npx electron-builder --dir "--arch" "x64" "--config" "electron-builder64.yml"

  • electron-builder version=20.44.4
  • loaded configuration file=/home/simon/ytmdesktop-git/src/ytmdesktop/electron-builder64.yml
  • writing effective config file=dist/builder-effective-config.yaml
Error: Unresolved node modules: bufferutil, utf-8-validate
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/util/packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/util/packageDependencies.ts:88:81)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/util/packageDependencies.ts:83:18
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Collector.collect (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/util/packageDependencies.ts:76:28)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/util/packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
    at _getProductionDependencies (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/packageDependencies.js:92:37)
    at getProductionDependencies (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/packageDependencies.js:83:37)
    at Lazy.<anonymous> (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:138:24)
    at Generator.next (<anonymous>)
    at Lazy.get value [as value] (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/lazy-val/src/main.ts:18:25)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/yarn.js:166:90
From previous event:
    at _getProductionDependencies (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/packageDependencies.js:92:37)
    at getProductionDependencies (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/packageDependencies.js:83:37)
    at Lazy.<anonymous> (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:138:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/lazy-val/src/main.ts:18:25)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/yarn.js:166:90
    at Generator.next (<anonymous>)
From previous event:
    at _rebuild (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/util/yarn.ts:179:5)
    at rebuild (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/yarn.js:163:19)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/util/yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at _installOrRebuild (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/yarn.js:71:28)
    at installOrRebuild (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/out/util/yarn.js:55:28)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:509:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:470:70)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/graceful-fs/graceful-fs.js:136:16
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:154:23)
From previous event:
    at Packager._build (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Packager.build (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/electron-builder/src/builder.ts:228:10)
    at /home/simon/ytmdesktop-git/src/ytmdesktop/node_modules/electron-builder/src/cli/cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-music-desktop-app@1.8.0 pack: `npx electron-builder --dir "--arch" "x64" "--config" "electron-builder64.yml"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-music-desktop-app@1.8.0 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/simon/.npm/_logs/2020-01-10T12_39_07_708Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-music-desktop-app@1.8.0 pack:x64: `npm run pack -- --arch x64 --config electron-builder64.yml`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-music-desktop-app@1.8.0 pack:x64 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/simon/.npm/_logs/2020-01-10T12_39_07_743Z-debug.log
```
However, a workaround is to set ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES to true when running the npm build.

**Comment by garfunkel** [comment]
@MarkoShiva try to upgrade now.

**Comment by adlerluiz** [comment]
Hello @garfunkel 

Some dependencies now use these packages 'bufferutil' and 'utf-8-validate' but not added in their own dependencies, I will add in package.json

**Comment by garfunkel** [comment]
Ah nice one, thanks.

I'll update the AUR package a little later once that's done to remove the workaround.

**Comment by adlerluiz** [comment]
Today I will release v1.8.1 to fix it and another things.

Thank you.

**Comment by MarkoShiva** [comment]
Thanks I will update.

**Comment by MarkoShiva** [comment]
It works.

**Comment by rickinbsb** [comment]
perfect!
