### ISSUE TITLE
Run in WSL?

### ISSUE THREAD

**Issue by rosostolato** [ytmdesktop/ytmdesktop#876]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I'm trying to run it under WSL2 on windows. I don't know if it's possible, but it should be since it's just an electron app.

### Expected Behavior

It should work.

### Steps To Reproduce

1. Build it in a WSL terminal
2. Run it
3. See the error

```
App threw an error during load
Error: unknown address type:disabled
    at createStream (/usr/lib/ytmdesktop/resources/app.asar/node_modules/dbus-next/lib/connection.js:57:17)
    at createConnection (/usr/lib/ytmdesktop/resources/app.asar/node_modules/dbus-next/lib/connection.js:73:31)
    at createClient (/usr/lib/ytmdesktop/resources/app.asar/node_modules/dbus-next/index.js:9:20)
    at Object.sessionBus (/usr/lib/ytmdesktop/resources/app.asar/node_modules/dbus-next/index.js:40:10)
    at Player.init (/usr/lib/ytmdesktop/resources/app.asar/node_modules/mpris-service/src/index.js:183:20)
    at new Player (/usr/lib/ytmdesktop/resources/app.asar/node_modules/mpris-service/src/index.js:175:8)
    at Mpris.start (/usr/lib/ytmdesktop/resources/app.asar/src/providers/mprisProvider.js:12:23)
    at Object.<anonymous> (/usr/lib/ytmdesktop/resources/app.asar/main.js:115:19)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: unknown address type:disabled
    at createStream (/usr/lib/ytmdesktop/resources/app.asar/node_modules/dbus-next/lib/connection.js:57:17)
    at createConnection (/usr/lib/ytmdesktop/resources/app.asar/node_modules/dbus-next/lib/connection.js:73:31)
    at createClient (/usr/lib/ytmdesktop/resources/app.asar/node_modules/dbus-next/index.js:9:20)
    at Object.sessionBus (/usr/lib/ytmdesktop/resources/app.asar/node_modules/dbus-next/index.js:40:10)
    at Player.init (/usr/lib/ytmdesktop/resources/app.asar/node_modules/mpris-service/src/index.js:183:20)
    at new Player (/usr/lib/ytmdesktop/resources/app.asar/node_modules/mpris-service/src/index.js:175:8)
    at Mpris.start (/usr/lib/ytmdesktop/resources/app.asar/src/providers/mprisProvider.js:12:23)
    at Object.<anonymous> (/usr/lib/ytmdesktop/resources/app.asar/main.js:115:19)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
```

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

building on WSL

**Comment by Alipoodle** [comment]
Can I ask why you wish to run this within WSL?

We have a version already for Windows machines, with WINDOWS SPECIFIC features. I'm not really seeing enough love for WSL to really feel like we should be adding in a bunch of stuff to remove a lot of the LINUX features while building in a WSL.

**Comment by rosostolato** [comment]
@Alipoodle because I can't sign in using the windows app because of this issue https://github.com/ytmdesktop/ytmdesktop/issues/866. And I can make it work on linux os, so I just wanted to test it using WSL.

**Comment by Alipoodle** [comment]
Have you tried using the 1.14.1 nightly version to fix it.
I doubt that there will be any difference regarding fixing of #866 in Linux over Windows.

WSL has had no discussion over doing work for and likely won't.
It seems strange to basically have a Extremely cut down version of YTMD as it will support non of the Linux or Windows Specific features.
Linux features will not function due to lacking the actual real Linux Environment so likely failing to run a dozen things on it (such as the dbus needed for Media information shown above),
and Windows features not compiling without MSBuild, which I feel will likely not function within yarn & node-gyp the same intended way. (NodeRT's Windows tools are Hard coded to VS 2015 paths on Windows, so will fail already)

**Comment by Alipoodle** [comment]
Closing this in Favor of #860
