### ISSUE TITLE
Bug: Snap is unable to chown the config

### ISSUE THREAD

**Issue by AndrewBarber** [ytmdesktop/ytmdesktop#90]
Hi there,

Launching youtube-music-desktop-app on Ubuntu 19.04 is causing the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/andrew/snap/youtube-music-desktop-app/1/.config/youtube-music-desktop-app/config.json.515862474'
    at Object.chownSync (fs.js:1104:3)
    at Function.writeFileSync [as sync] (/snap/youtube-music-desktop-app/1/resources/app.asar/node_modules/write-file-atomic/index.js:198:27)
    at ElectronStore.set store [as store] (/snap/youtube-music-desktop-app/1/resources/app.asar/node_modules/conf/index.js:267:19)
    at ElectronStore.set (/snap/youtube-music-desktop-app/1/resources/app.asar/node_modules/conf/index.js:152:14)
    at set (/snap/youtube-music-desktop-app/1/resources/app.asar/providers/settingsProvider.js:18:9)
    at Object.setInitialValue (/snap/youtube-music-desktop-app/1/resources/app.asar/providers/settingsProvider.js:28:5)
    at Object.<anonymous> (/snap/youtube-music-desktop-app/1/resources/app.asar/utils/defaultSettings.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
```

I think this is likely due to permissions that snaps have? However, I'm unsure how to remedy this!

**Comment by adlerluiz** [comment]
@rickinbsb can you help?

**Comment by rickinbsb** [comment]
sure! I'll try to reproduce this

**Comment by AndrewBarber** [comment]
I've done some digging on this one.

So it seems that the issue lies within [write-file-atomic](https://github.com/npm/write-file-atomic/issues/49) which is used by [electron-store](https://github.com/sindresorhus/electron-store/issues/75).

**Comment by pallebone** [comment]
Hi I am also affected by this bug. Running Ubuntu Mate 20.04

**Comment by rickinbsb** [comment]
Thanks for the research @AndrewBarber
