### ISSUE TITLE
Miniplayer just... keeps... growing

### ISSUE THREAD

**Issue by ScottBeeson** [ytmdesktop/ytmdesktop#909]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Mini player just grows, pixel by pixel...

When I exit mini player, I get the following error:

> [Window Title]
> Error
> 
> [Main Instruction]
> A JavaScript error occurred in the main process
> 
> [Content]
> Uncaught Exception:
> TypeError: Cannot read property 'setSize' of undefined
>     at Timeout._onTimeout (C:\Users\ScottBeeson\AppData\Local\Programs\youtube-music-desktop-app\resources\app.asar\main.js:1178:36)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7)
> 
> [OK]

Also, see https://github.com/ytmdesktop/ytmdesktop/issues/618

### Expected Behavior

I expect it not to grow!

### Steps To Reproduce

1. Open YTMD
2. Play a song
3. Switch to mini-player
4. Watch it grow like a chia-pet!

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

Exe

### Anything else?

![ytmdgrowth](https://user-images.githubusercontent.com/108358/153903217-2f044eb7-fe6d-411d-ba78-529696e9f9b2.gif)

**Comment by ScottBeeson** [comment]
I installed 1.12.1 and 1.12.0 and both exhibited the same issue.  I confirmed the version number in the about page.

**Comment by ScottBeeson** [comment]
Sorry, just found https://github.com/ytmdesktop/ytmdesktop/issues/379
